### PR TITLE
Add CrashlyticsNdk

### PR DESCRIPTION
**Pull request by GreenAppers**
This needs a test but should work.  I was only able to test the feature/optOut branch.

### CODE REVIEW

**Comment by jaumard** [comment]
Can you update the Readme with a section "Android NDK" to let people know how to enable it and update the example app to have it enabled please ?

Why can't you test master ?

**Comment by GreenAppers** [comment]
Will do.  I tested that the changes compile.  But I only have a reproducible crash bug for my compileSdkVersion 27 app.  Eventually I can setup a native crash to test master as well.

**Comment by jaumard** [comment]
Hey @GreenAppers ! Plugin was migrate to java :) to avoir Kotlin version problems can you rebase please ? I'll merge this and publish a new version

**Comment by jaumard** [comment]
Thanks @GreenAppers !

**Pull request merged**
