### PR TITLE
Add CrashlyticsNdk

### PR DESCRIPTION
**Pull request by GreenAppers**
Opening a PR for discussion.  The changes build successfully, but it still doesn't seem to catch SIGSEGV.

### CODE REVIEW

**Comment by GreenAppers** [comment]
These changes actually work!  The user needs to add "crashlytics { enableNdk true }" after apply plugin: 'io.fabric' in their build.gradle.

I see no reason why this shouldn't be the recommended default.  Clearly native crashes are possible despite pure Dart primary projects, as I'm currently debugging one.  Must it be due to the platform channels of one of my dependencies?

The last step is to get the stacktrace symbolicated.

**Comment by jaumard** [comment]
Hi @GreenAppers ! Thanks for bringing this on the table :) for sure I don't see any problem adding this, more crash you are able to get more you'll be able to see and improve the stability of your app, 
Can you update the Readme with a section "Android NDK" to let people know how to enable it and update the example app to have it enabled please ?

**Comment by GreenAppers** [comment]
Hi @jaumard.  Thanks for flutter_crashlytics!  Ok, sounds good!  I'm currently researching symbolication and I'll update once I have it working.  At a minimum it will mean adding the enableNdk to build.gradle and also adding gradlew crashlyticsUploadSymbolsRelease to the app release script.

**Comment by jaumard** [comment]
Hey @GreenAppers I'll close this PR as I can't merge it, this branch is old, you should update your second PR that use master instead :). Thanks !

**Pull request closed without merging**
